<?php echo '<?php' ?>

/**
 * <?php echo $this->package_description.PHP_EOL; ?>
 * @package <?php echo $this->package.PHP_EOL; ?>
 * @subpackage <?php echo $this->subpackage.PHP_EOL; ?>
 */

<?php
foreach($this->dependencies as $dependency):
    echo 'use ' . $dependency . ';' . PHP_EOL;
endforeach;
?>

<?php foreach($this->relationships as $relationship):
if ($relationship instanceof \Zend\Ext\Views\C\Source\EnumDto) {
    //echo '// ' . $relationship->name . PHP_EOL;
    foreach($relationship->constants as $constant) {
        echo '/* ' . PHP_EOL;
        echo ' * ' . $this->commentHelper($constant->getDescription());
        echo ' */' . PHP_EOL;
        echo 'const ' . $constant->getName() .' = ' . $constant->getValue() . ';' . PHP_EOL;
    }
    echo PHP_EOL;
}
endforeach; ?>


/**
 * <?php echo $this->commentHelper($this->description) ?>
 */
class <?php echo $this->nameclassHelper($this->name) ?> <?php echo isset($this->extends)?'extends '.$this->extends:''; ?>
{
<?php foreach($this->properties as $property): ?>
    /**
     * <?php echo $this->commentHelper($property->short_description, '    ') ?>
     * <?php echo '@var '.$property->type.PHP_EOL; ?>
     */
<?php echo '    public $'.$property->name.';'.PHP_EOL; ?>
<?php endforeach; ?>
}
<?php foreach($this->methods as $key=>$method): ?>
<?php
echo $this->methodHelper($method);
?>
<?php endforeach; ?>


<?php foreach($this->relationships as $relationship):
if ($relationship instanceof \Zend\Ext\Views\C\UnionDto) {
    echo '/* ' . PHP_EOL;
    echo ' * ' . $this->commentHelper($relationship->description);
    echo ' */' . PHP_EOL;
    echo 'class ' . $relationship->name .' {' . PHP_EOL;
    foreach($relationship->members as $member) {
        echo '    /* ' . PHP_EOL;
        echo '     * ' . $this->commentHelper($member->getDescription());
        //echo '     * @var ' . $member->getType()->getName() . PHP_EOL;
        echo '     */' . PHP_EOL;
        echo '    public $' .$member->getName() . ';' . PHP_EOL;
    }
    echo '}' . PHP_EOL;
}
endforeach; ?>
