<?php echo '<?php' ?>

/**
 * Cairo graphics library
 * @package <?php echo $this->namespace.PHP_EOL; ?>
 */

<?php
/**
 * <?php echo $this->commentHelper($constant->short_description, '') ?>
 * <?php echo '@var '.$constant->type.PHP_EOL; ?>
 */
/*
$i=0;
foreach($this->constants as $constant) {
    echo 'const '.$constant['name'];
    if (isset($constant['value'])) {
        echo ' = ' . $constant['value'];
        $i = intval($constant['value'])+1;
    } else {
        echo ' = ' . $i++;
    }
    echo ';'.PHP_EOL;

}
*/
?>


<?php foreach($this->methods as $key=>$method): ?>
<?php
echo $this->methodHelper($method);
?>
<?php endforeach; ?>
