
/**
<?php

echo $this->commentHelper($this->short_description);

foreach($this->parameters as $parameter) {
    echo ' * @param '.$parameter->type;
    echo ' ';
    echo '$'.$parameter->name;
    echo ' ';
    echo $parameter->short_description;
    echo PHP_EOL;
    if ('void'!=$this->type) {
        echo ' * @return '.$this->type;
        echo PHP_EOL;
    }
}

?>
 */
function <?php echo $this->name; ?>(<?php
$glue = '';
foreach($this->parameters as $parameter) {
    echo $glue;
    //echo $this->parameterHelper($parameter);
    echo $parameter->type;
    echo ' $';
    echo $parameter->name;
    $glue = ', ';
}
?>)<?php
if ('void'!=$this->type) {
    echo ':'.$this->type;
    echo ' ';
}
?>

{<?php

$msg='\'Error: Forbidden include_path "\' . __DIR__ . \'"\'';
switch ($this->type) {
    case 'double':
    case 'float':
            echo 'die('.$msg.'); return 0.0;';
        break;
    case 'int':
        echo 'die('.$msg.'); return 0;';
        break;
    case 'bool':
        echo 'die('.$msg.'); return true;';
        break;
    case 'void':
        echo 'die('.$msg.');';
        break;
    default:
        echo 'die('.$msg.'); return new '.$this->type.'();';
        break;
}
?>}

