/**
<?php echo $this->commentHelper($this->short_description);
foreach($this->parameters as $parameter) {
    echo ' * @param '.$this->typeHelper($parameter->getType(), True);
    echo ' ';
    echo '$'.$this->namepropertyHelper($parameter->getName());
    echo ' ';
    echo $this->commentHelper($parameter->getDescription());
}
if ('void'!=$this->method->getType()->getName()) {
    echo ' * @return '.$this->typeHelper($this->method->getType());
    echo PHP_EOL;
}
?>
 */
function <?php echo $this->namemethodHelper($this->method) ?> (<?php
$glue = '';
foreach($this->parameters as $parameter) {
    echo $glue;
    echo $this->parameterHelper($parameter);
    $glue = ', ';
}
?>): <?php
echo $this->typeHelper($this->type)
?>{ }
