<?php

$name_function = $this->nameclassHelper($this->name);
$name_macro = strtoupper($name_function);
$has_members = count($this->members);

?>#ifndef PHP_<?php echo $name_macro ?>_H
#define PHP_<?php echo $name_macro ?>_H

#define PHP_<?php echo $name_macro ?>_FE() \
<?php foreach($this->methods as $method): ?>
    PHP_GTK_FE(<?php echo $method->name ?>,<?php echo $method->pad ?> arginfo_<?php echo $method->name ?>) \
<?php endforeach; ?>

#define PHP_<?php echo $name_macro ?>_MINIT_FUNCTION(container_ce, parent_ce) \
    php_<?php echo $name_function ?>_class_init(container_ce, parent_ce)

#define PHP_<?php echo $name_macro ?>_MSHUTDOWN_FUNCTION() { \
}

#define PHP_<?php echo $name_macro ?>_RSHUTDOWN_FUNCTION() {\
}

zend_class_entry*
php_<?php echo $name_function ?>_class_init(zend_class_entry *container_ce, zend_class_entry *parent_ce);

<?php
echo $this->implementation->writeFunctions(true);
?>

<?php foreach($this->methods as $method): ?>
<?php echo $method->args; ?>
PHP_FUNCTION(<?php echo $method->name ?>);

<?php endforeach; ?>

#endif	/* PHP_<?php echo $name_macro ?>_H */
