
#define PHP_<?php echo $this->nameMacro ?>_FE() \
<?php foreach($this->methods as $name=>$method): ?>
    PHP_GTK_FE(<?php echo $name ?>,<?php echo $method->pad ?> arginfo_<?php echo $name ?>) \
<?php endforeach; ?>

#define PHP_<?php echo $this->nameMacro ?>_MINIT_FUNCTION(container_ce, parent_ce) \
    php_<?php echo $this->nameFunction ?>_class_init(container_ce, parent_ce)

#define PHP_<?php echo $this->nameMacro ?>_MSHUTDOWN_FUNCTION() { \
}

#define PHP_<?php echo $this->nameMacro ?>_RSHUTDOWN_FUNCTION() {\
}

<?php foreach($this->methods as $name=>$method): ?>
<?php echo $this->argHelper($method->generator); ?>
<?php if(False): ?>
ZEND_BEGIN_ARG_INFO_EX(arginfo_<?php echo $name ?>, 0, ZEND_SEND_BY_VAL, <?php echo count($method->parameters) ?>)
<?php foreach($method->parameters as $parameter): ?>
    ZEND_ARG_INFO(ZEND_SEND_BY_VAL, <?php echo $parameter->name ?>)
<?php endforeach; ?>
ZEND_END_ARG_INFO()
<?php endif; ?>
PHP_FUNCTION(<?php echo $name ?>);

<?php endforeach; ?>
