<?php
$params = '';
$args = '';
if (isset($function_create)) {
    $comma = '';
    foreach ($function_create->parameters as $parameter) {
        $args .= $comma;
        $args .= $parameter->type;
        $args .= ' ';
        $args .= $parameter->name;

        $params .= $comma;
        $params .= $parameter->name;

        $comma = ', ';
    }
}
?>
php_<?php echo $name_function ?>*
php_<?php echo $name_function ?>_new(<?php echo $args; ?>)
{
    zend_object *z_object = php_<?php echo $name_function ?>_create_object(php_<?php echo $name_function ?>_class_entry);
    php_<?php echo $name_function ?> *php_object = ZOBJ_TO_PHP_<?php echo $name_macro ?>(z_object);

<?php if (isset($function_create)): ?>
    php_object->ptr = <?php echo $function_create->call; ?>(<?php echo $params; ?>);
<?php else: ?>
    php_object->ptr = ptr;//cairo_create();
<?php endif; ?>

    return php_object;
}
