/**
 * Cairo project (https://www.cairographics.org/)
 *
 * @link      https://gitlab.freedesktop.org/cairo/cairo for the canonical source repository
 * @copyright Copyright 2020 (c) Free Software Foundation. (https://www.fsf.org/)
 * @license   https://spdx.org/licenses/LGPL-2.1-or-later.html Mozilla Public License 1.1
 */

/**
 * Cairo: A Vector Graphics Library
 *
 * cairo_t is the main object used when drawing with cairo.
 * To draw with cairo, you create a cairo_t, set the target surface,
 * and drawing options for the cairo_t, create shapes with functions
 * like cairo_move_to() and cairo_line_to(), and then draw shapes
 * with cairo_stroke() or cairo_fill().
 *
 */
