<?php

$ns = strtoupper($this->namespaceHelper($this->name));
$name_function = $this->nameclassHelper($this->name);
$name_function = strtolower($name_function);
$name_macro = strtoupper($name_function);
$has_members = count($this->members);

?>
<?php echo $this->license; ?>

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <php.h>
#include <php_ini.h>
#include <zend_interfaces.h>
#include <ext/standard/info.h>

<?php
foreach($this->requires as $require) {
    echo '#include <' . $require .'>' . PHP_EOL;
}
echo PHP_EOL;

echo '#include "php_gtk.h"' . PHP_EOL;
foreach($this->dependencies as $dependency) {
    if (empty($dependency)) {
        echo PHP_EOL;
        continue;
    }
    echo '#include "' . $dependency .'"' . PHP_EOL;
}

?>


extern HashTable         classes;
extern zend_module_entry gtk_module_entry;

<?php echo $this->implementation->writeDefine(); ?>


/*----------------------------------------------------------------------+
 | PHP_MINIT                                                            |
 +----------------------------------------------------------------------*/

 /*{{{ php_<?php echo $name_function ?>_class_init */
zend_class_entry*
php_<?php echo $name_function ?>_class_init(zend_class_entry *container_ce, zend_class_entry *parent_ce) {

<?php $allow=false; $previous = $this->since; ?>
<?php foreach($this->constants as $constant): ?>
<?php if ($allow && $constant->since!=$previous): ?>#endif<?php echo PHP_EOL; endif; ?>
<?php if ($constant->since > $this->since && $constant->since!=$previous): ?>#if <?php echo $ns ?>_VERSION >= <?php $allow=true; echo $constant->since.PHP_EOL; endif; ?>
<?php $previous = $constant->since; ?>
    zend_register_long_constant("<?php echo $constant->name ?>", sizeof("<?php echo $constant->name ?>")-1,
        <?php echo $constant->name ?>, CONST_CS | CONST_PERSISTENT, gtk_module_entry.module_number);
<?php endforeach; ?>
<?php if ($allow): ?>#endif<?php echo PHP_EOL; endif; ?>

    return NULL;
}/*}}} */

/*----------------------------------------------------------------------+
 | Zend-User utils                                                      |
 +----------------------------------------------------------------------*/
<?php
echo $this->implementation->writeFunctions(false);
?>

/*----------------------------------------------------------------------+
 | Zend-User API                                                        |
 +----------------------------------------------------------------------*/

/*----------------------------------------------------------------------+
 | PHP_METHOD                                                           |
 +----------------------------------------------------------------------*/

/*----------------------------------------------------------------------+
 | PHP_FUNCTION                                                         |
 +----------------------------------------------------------------------*/

<?php $allow=false; $previous = $this->since; ?>
<?php foreach($this->methods as $name=>$method): ?>
<?php if ($allow && $method->since!=$previous): ?>#endif<?php echo PHP_EOL; endif; ?>
<?php if ($method->since > $this->since && $method->since!=$previous): ?>#if <?php echo $ns ?>_VERSION >= <?php $allow=true; echo $method->since.PHP_EOL; endif; ?>
<?php $previous = $method->since; ?>
/* {{{ <?php echo $method->docblock ?> */
PHP_FUNCTION(<?php echo $method->name ?>)
{
<?php echo $method->args.PHP_EOL; ?>
<?php echo $method->call.PHP_EOL; ?>
<?php echo $method->return.PHP_EOL; ?>
}/* }}} */

<?php endforeach; ?>
<?php if ($allow): ?>#endif<?php echo PHP_EOL; endif; ?>
