/* {{{ php_<?php echo $name_function ?>_free_object */
static void
php_<?php echo $name_function ?>_free_object(zend_object *object)
{
    php_<?php echo $name_function ?> *intern = ZOBJ_TO_PHP_<?php echo $name_macro ?>(object);

<?php if (!empty($destroy_function)): ?>
    if (intern->ptr) {
        <?php echo $destroy_function, '(intern->ptr);', PHP_EOL; ?>
        intern->ptr = NULL;
    }
<?php endif; ?>

<?php

/*if (empty($this->members)) {
    echo '    if (intern->ptr) {'.PHP_EOL;
    //echo $this->implementation->zend_extends('free_object');
    echo '        intern->ptr = NULL;'.PHP_EOL;
    echo '    }'.PHP_EOL;
} else {
    foreach($this->members as $property) {
        echo '    zval_ptr_dtor(&intern->'.$property->name.');'.PHP_EOL;
    }
}*/
?>
    zend_object_std_dtor(&intern->std);
}/* }}} */
