#!/usr/bin/php
<?php
/* $] ./generate --version=3
"3.22.30" */

/*
get all version of PHP
<php-src>$ git ls-remote --tags > /home/dev/Projects/php_tags.txt
$tags='';
$lines = file('/home/dev/Projects/php_tags.txt');
foreach($lines as $line) {
    if(preg_match('#refs/tags/(php-[4578]\.[0-9]+\.[0-9]+)$#', $line, $matches)) {
        $tags .= $matches[1] . "\n";
    }
}
file_put_contents('/home/dev/Projects/php_tags.txt', $tags);

exit();*/

require_once __DIR__ . '/../vendor/autoload.php';

use Zend\Ext\Services\CodeGenerator;
use Zend\Ext\Services\CodeGenerator\Php8 as Php8CodeGenerator;
use Zend\Ext\Services\DocBook\Glib as GlibDocBook;
use Zend\Ext\Services\SourceCode\Glib as GlibSourceCode;

define('APP_DIR', realpath(__DIR__.'/..'));

$tag = '2.56.4';
$log_dir = APP_DIR."/log/glib-$tag";
$tmp_dir = APP_DIR.'/tmp';
$output_dir = APP_DIR.'/output';
$log = $log_dir.'/log.txt';

`mkdir -p $log_dir`;
`mkdir -p $output_dir`;
`mkdir -p $output_dir/API`;
//`chmod u+w $log_dir`;


`touch $log`;
`touch $output_dir/API/GHashTable.php`;
`touch $output_dir/g-hash-table.c`;


`echo "Starting..." > $log`;

//`echo "Add log" >> $log`;
//`git clone https://github.com/GNOME/glib.git > $log`;
//`git checkout tags/$tag -b <branch>`

$src_dir = '/home/dev/Projects/glib';
$build_dir = '/home/dev/Projects/glib-build-doc';
$service = new GlibSourceCode($src_dir, $build_dir);
$service->addBlackList(array('STRUCT'=>array('utimbuf', 'GMarkupParser')));
$service->loadTypes();

$servicePhp = new Php8CodeGenerator();


// compare glib-decl vs glib docBook
$docBook = new GlibDocBook();
$docBook->addSourceCode($service);
$docBook->addCodeGenerator($servicePhp);
$docBook->load(/*doc.sgml*/);

/*
$servicePhp->setCode(CodeGenerator::PHP_CODE);
$servicePhp->setStyle(CodeGenerator::PP_STYLE);
$code = $docBook->save('/home/dev/Projects/gtkphp/output');
file_put_contents("$output_dir/API/GHashTable.php", $code);
*/

$servicePhp->setCode(CodeGenerator::C_CODE);
$servicePhp->setStyle(CodeGenerator::C_HEADER_STYLE);
$code = $docBook->save('php_g');
file_put_contents("$output_dir/g-list.h", $code);

/*
$servicePhp->setCode(CodeGenerator::C_CODE);
$servicePhp->setStyle(CodeGenerator::C_SOURCE_STYLE);
$code = $docBook->save('php_g');
file_put_contents("$output_dir/g-list.c", $code);
*/

// Output php-doc
// Output php-x.x.x API
// Output php-x.x.x Wrapper
// Output zend_code_extension
