<?php echo '<?xml version="1.0" encoding="utf-8"?>' ?>
<!-- $Revision$ -->
<phpdoc:classref xmlns:phpdoc="http://php.net/ns/phpdoc" xml:id="class.<?php echo strtolower($this->name) ?>" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude">
    <title>The <?php echo $this->name ?> class</title>
    <titleabbrev><?php echo $this->name ?></titleabbrev>

    <partintro>

        <!-- {{{ <?php echo $this->name ?> intro -->
        <section xml:id="<?php echo strtolower($this->name) ?>.intro">
            &reftitle.intro;
            <para>
                <?php echo $this->commentHelper($this->description) ?>
            </para>
        </section>
        <!-- }}} -->

        <section xml:id="<?php echo strtolower($this->name) ?>.synopsis">
            &reftitle.classsynopsis;

            <!-- {{{ Synopsis -->
            <classsynopsis>
                <ooclass><classname><?php echo $this->name ?></classname></ooclass>

                <!-- {{{ Class synopsis -->
                <classsynopsisinfo>
                    <ooclass>
                        <classname><?php echo $this->name ?></classname>
                    </ooclass>

                    <oointerface>
                        <interfacename>GtkBuildable</interfacename>
                    </oointerface>
                </classsynopsisinfo>
                <!-- }}} -->

                <classsynopsisinfo role="comment">&Methods;</classsynopsisinfo>
                <xi:include xpointer="xmlns(db=http://docbook.org/ns/docbook) xpointer(id('class.<?php echo strtolower($this->name) ?>')/db:refentry/db:refsect1[@role='description']/descendant::db:constructorsynopsis[1])" />
                <xi:include xpointer="xmlns(db=http://docbook.org/ns/docbook) xpointer(id('class.<?php echo strtolower($this->name) ?>')/db:refentry/db:refsect1[@role='description']/descendant::db:methodsynopsis[1])" />
            </classsynopsis>
            <!-- }}} -->

        </section>

    </partintro>

    &reference.<?php echo strtolower($this->namespaceHelper($this->name)) ?>.entities.<?php echo strtolower($this->name) ?>;

</phpdoc:classref>

<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-omittag:t
sgml-shorttag:t
sgml-minimize-attributes:nil
sgml-always-quote-attributes:t
sgml-indent-step:1
sgml-indent-data:t
indent-tabs-mode:nil
sgml-parent-document:nil
sgml-default-dtd-file:"~/.phpdoc/manual.ced"
sgml-exposed-tags:nil
sgml-local-catalogs:nil
sgml-local-ecat-files:nil
End:
vim600: syn=xml fen fdm=syntax fdl=2 si
vim: et tw=78 syn=sgml
vi: ts=1 sw=1
-->