<?php echo '<?xml version="1.0" encoding="utf-8"?>'.PHP_EOL ?>
<!-- $Revision$ -->
<?php //echo $this->license; ?>
<appendix xml:id="<?php echo strtolower($this->name) ?>.constants" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
 &reftitle.constants;
 &extension.constants;

 <table>
   <title>Enumerations</title>

<?php foreach ($this->objects as $objectDto): ?>
<?php echo $this->objectHelper($objectDto); ?>
<?php endforeach; ?>

  </table>

</appendix>

<?php //echo $this->vimMarks; ?>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-omittag:t
sgml-shorttag:t
sgml-minimize-attributes:nil
sgml-always-quote-attributes:t
sgml-indent-step:1
sgml-indent-data:t
indent-tabs-mode:nil
sgml-parent-document:nil
sgml-default-dtd-file:"~/.phpdoc/manual.ced"
sgml-exposed-tags:nil
sgml-local-catalogs:nil
sgml-local-ecat-files:nil
End:
vim600: syn=xml fen fdm=syntax fdl=2 si
vim: et tw=78 syn=sgml
vi: ts=1 sw=1
-->