    <tgroup cols="1">
      <thead>
        <row>
          <entry><?php echo $this->name ?></entry>
        </row>
      </thead>
      <tbody>
        <row>
          <entry><?php echo $this->description ?></entry>
        </row>
        <row>
          <entry><!--
            Note:
          --></entry>
        </row>
        <row>
          <entry>
            <variablelist>
<?php foreach($this->constants as $constant): ?>
              <varlistentry>
                <term>
                  <constant xml:id="constant.<?php echo $constant->name ?>"><?php echo $constant->name ?></constant>
                  (<type>int</type>)
                </term>
                <listitem>
                  <simpara>
                    <?php echo $constant->description ?>

                  </simpara>
                  <note>
                    <para>
                      Only available in Libcairo &gt;= 1.0.0
                    </para>
                  </note>
                </listitem>
              </varlistentry>
<?php endforeach; ?>
            </variablelist>
          </entry>
        </row>
      </tbody>
    </tgroup>

