<refentry xml:id="function.<?php echo $this->name ?>" xmlns="http://docbook.org/ns/docbook">
  <refnamediv>
    <refname><?php echo $this->name ?></refname>
    <refpurpose><?php echo $this->documentation->refpurpose($this->name) ?></refpurpose>
  </refnamediv>

  <refsect1 role="description">
    &reftitle.description;
    <methodsynopsis>
<?php echo $this->call ?>
<?php echo $this->args ?>
    </methodsynopsis>
    <?php echo $this->description ?>
  </refsect1>

<?php if(count($this->parameters)): ?>
  <refsect1 role="parameters">
    &reftitle.parameters;
    <para>
      <variablelist>
<?php foreach($this->parameters as $parameter): ?>
        <varlistentry>
          <term><parameter><?php echo $parameter->name ?></parameter></term>
          <listitem>
            <?php echo $parameter->description.PHP_EOL ?>
          </listitem>
        </varlistentry>
<?php endforeach; ?>
      </variablelist>
    </para>
  </refsect1>
<?php endif; ?>

    <refsect1 role="returnvalues">
        &reftitle.returnvalues;
<?php echo $this->return ?>
    </refsect1>
    
    <?php echo $this->documentation->example($this->name) ?>

    <refsect1 role="seealso">
        &reftitle.seealso;
        <para>
            <simplelist>
                <member><methodname>GtkWindow::registerXPathNamespace</methodname></member>
                <member><methodname>GtkWindow::getDocNamespaces</methodname></member>
                <member><methodname>GtkWindow::getNamespaces</methodname></member>
                <member><xref linkend="gtkml.examples-basic"/></member>
            </simplelist>
        </para>
    </refsect1>

</refentry>
