PHP_FUNCTION(g_list_nth)
{
    zval *zlist;
    zend_long n;

    ZEND_PARSE_PARAMETERS_START(2, 2)
        Z_PARAM_OBJECT_OF_CLASS_EX(zlist, php_g_list_class_entry, 0, 0);
        Z_PARAM_LONG(n);
    ZEND_PARSE_PARAMETERS_END();

    php_g_list *php_list = ZVAL_IS_PHP_G_LIST(zlist)? ZVAL_GET_PHP_G_LIST(zlist): NULL;

    php_g_list *php_ret = php_g_list_nth(php_list, n);
    zend_object *z_ret = &php_ret->std;

    RETURN_OBJ(z_ret);
}
