static zend_object*
php_g_list_create_object(zend_class_entry *class_type)
{
    php_g_list *intern = zend_object_alloc(sizeof(php_g_list), class_type);
    zend_object_std_init(&intern->std, class_type);
    object_properties_init(&intern->std, class_type);


    ZVAL_NULL(&intern->data);
    ZVAL_NULL(&intern->next);
    ZVAL_NULL(&intern->prev);

    intern->std.handlers = &php_g_list_handlers;

    return &intern->std;
}
