PHP_FUNCTION(g_list_insert)
{
    zval *zlist;
    zval *zdata;
    zend_long position;

    ZEND_PARSE_PARAMETERS_START(3, 3)
        Z_PARAM_OBJECT_OF_CLASS_EX(zlist, php_g_list_class_entry, 1, 0);
        Z_PARAM_ZVAL(zdata);
        Z_PARAM_LONG(position);
    ZEND_PARSE_PARAMETERS_END();

    php_g_list *php_list = ZVAL_IS_PHP_G_LIST(zlist)? ZVAL_GET_PHP_G_LIST(zlist): NULL;

    php_g_list *php_ret = php_g_list_insert(php_list, zdata, position);

    RETURN_OBJ(&php_ret->std);
}
