name: Test-Unit

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test-unit:
    # Name the Job
    name: Test code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: git clone https://github.com/gtkphp/zend-ext.git && cd zend-c && git checkout CI-start

      # Runs the Super-Linter action
      - name: Run Test-Unit
        uses: pwd
        env:
          DEFAULT_BRANCH: IC-start
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
