name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v2

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v7
        with:
          bootstrap: vendor/autoload.php
          php_version: 7.2.*
          configuration: test/phpunit.xml
          args: --coverage-text
